name: muon-telescope
channels:
- anaconda
- cogsci
- defaults
- nlesc
- vpython
dependencies:
- jupyter
- numpy
- pandas
- python=3.5
# - pyopengl
# - root_numpy
- vpython
# - pip:
#  - git+https://github.com/scikit-hep/root_pandas.git#egg=root_pandas